[package]
name = "tagger-setup"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["process", "fs", "io-util"] }
tracing = { workspace = true }
